# Generated by Django 2.2.4 on 2021-05-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='user_who_like',
            field=models.ManyToManyField(related_name='liked_quote', to='q.User'),
        ),
    ]
